### ISSUE TITLE
Cloudflare ddns api key ENV not valid 

### ISSUE THREAD

**Issue by dan3805** [dockserver/dockserver#516]
the global api key does not work for the cloudflare ddns setup, so you have to create an api key.

[Creating a Cloudflare API token : oznu/cloudflare-ddns](https://hub.docker.com/r/oznu/cloudflare-ddns/)

```
[cont-init.d] 30-cloudflare-setup: executing... 
----------------------------------------------------------------
ERROR: Invalid CloudFlare Credentials - 400
----------------------------------------------------------------
Make sure the API_KEY is correct. You can
get your scoped CloudFlare API Token here:
https://dash.cloudflare.com/profile/api-tokens
```
I suggest adding a variable like this in the .env file
```
## CLOUDFLARE DDNS 
CLOUDFLARE_DDNS_API_KEY=${CLOUDFLARE_DDNS_API_KEY:-CF-DDNS-API-KEY-HERE}
```

```
---
version: "3.9"
## SET GLOBAL HEADER FOR COMPOSER
services:
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    hostname: cloudflare-ddns
    container_name: cloudflare-ddns
    restart: "${RESTARTAPP}"
    networks:
      - ${DOCKERNETWORK}
    environment:
      - "PGID=${ID}"
      - "PUID=${ID}"
      - "TZ=${TZ}"
      - "UMASK=${UMASK}"
      - "API_KEY=${CLOUDFLARE_DDNS_API_KEY}"
      - "ZONE=${DOMAIN}"
      - "PROXIED=true"
    labels:
      - "dockupdater.enable=true"
networks:
  proxy:
    driver: bridge
    external: true
    ```
